apiVersion: v2
name: redis-replication
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
version: 0.16.7
appVersion: "0.16.7"
type: application
engine: gotpl
maintainers:
  - name: iamabhishek-dubey
  - name: sandy724
  - name: shubham-cmyk
sources:
  - https://github.com/ot-container-kit/redis-operator
home: https://github.com/ot-container-kit/redis-operator
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
- redis-exporter
icon: https://github.com/OT-CONTAINER-KIT/redis-operator/raw/master/static/redis-operator-logo.svg
