{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if or (not .Values.rbac.scope) (eq .Values.rbac.scope "cluster") }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ .Values.redisOperator.name }}
{{- if eq .Values.rbac.scope "namespace" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app.kubernetes.io/name : {{ .Values.redisOperator.name }}
    helm.sh/chart : {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by : {{ .Release.Service }}
    app.kubernetes.io/instance : {{ .Release.Name }}
    app.kubernetes.io/version : {{ .Chart.AppVersion }}
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of : {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
{{- if or (not .Values.rbac.scope) (eq .Values.rbac.scope "cluster") }}
  kind: ClusterRole
{{- else }}
  kind: Role
{{- end }}
  name: {{ .Values.redisOperator.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
