{{- if .Values.redisExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisCluster.name | default .Release.Name }}-leader-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.redisCluster.name | default .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Values.redisCluster.name | default .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: metrics
    service-type: metrics
    role: leader
spec:
  type: ClusterIP
  ports:
    - name: redis-exporter
      port: 9121
      targetPort: 9121
      protocol: TCP
  selector:
    app: {{ .Values.redisCluster.name | default .Release.Name }}-leader
    redis_setup_type: cluster
    role: leader
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisCluster.name | default .Release.Name }}-follower-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.redisCluster.name | default .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Values.redisCluster.name | default .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: metrics
    service-type: metrics
    role: follower
spec:
  type: ClusterIP
  ports:
    - name: redis-exporter
      port: 9121
      targetPort: 9121
      protocol: TCP
  selector:
    app: {{ .Values.redisCluster.name | default .Release.Name }}-follower
    redis_setup_type: cluster
    role: follower
{{- end }}
