---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-operator
subjects:
- kind: ServiceAccount
  name: redis-operator
  namespace: redis-operator
roleRef:
  kind: ClusterRole
  name: redis-operator
  apiGroup: rbac.authorization.k8s.io

