apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
  namespace: ot-operators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-operator
  template:
    metadata:
      labels:
        name: redis-operator
    spec:
      serviceAccountName: redis-operator
      containers:
      - name: redis-operator
        image: quay.io/opstree/redis-operator:v0.2
        imagePullPolicy: Always
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "redis-operator"
