# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redissentinels.redis.redis.opstreelabs.in
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: ot-operators
          name: webhook-service
          path: /convert
      conversionReviewVersions: ["v1beta2", "v1beta1"]
