apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-sample
    app.kubernetes.io/part-of: redis-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: redis-operator
  name: redis-sample
spec:
  # TODO(user): Add fields here
