---
apiVersion: v2
version: 0.21.2
appVersion: "0.21.0"
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
engine: gotpl
maintainers:
  - name: iamabhishek-dubey
  
  - name: sandy724
  - name: shubham-cmyk
name: redis-operator
sources:
  - https://github.com/OT-CONTAINER-KIT/redis-operator
home: https://github.com/OT-CONTAINER-KIT/redis-operator
icon: https://github.com/OT-CONTAINER-KIT/redis-operator/raw/main/static/redis-operator-logo.svg
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
