apiVersion: v2
name: redis-sentinel
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
version: 0.16.0
appVersion: "0.16.0"
home: https://github.com/ot-container-kit/redis-operator
sources:
  - https://github.com/ot-container-kit/redis-operator
maintainers:
  - name: iamabhishek-dubey
  - name: sandy724
  - name: shubham-cmyk
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
- redis-exporter
icon: https://github.com/OT-CONTAINER-KIT/redis-operator/raw/master/static/redis-operator-logo.svg
type: application
